<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.common</groupId>
        <artifactId>service-parent-pom</artifactId>
        <version>17.104.0</version>
    </parent>

    <groupId>uk.gov.moj.cpp.prosecution.casefile</groupId>
    <artifactId>prosecutioncasefile-parent</artifactId>
    <version>17.0.96-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Prosecution Casefile Microservice - Parent</name>
    <description>Casefile Microservice - Prosecution Context</description>

    <properties>
        <jgitflow.maven.developBranchName>main</jgitflow.maven.developBranchName>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec
        </sonar.jacoco.itReportPath>
        <sonar.report.export.path>sonar-report.json</sonar.report.export.path>
        <sonar.scm.provider>git</sonar.scm.provider>
        <mvn.site.url>file://${project.build.directory}/site</mvn.site.url>
        <cpp.framework.action.mapping.enabled>true</cpp.framework.action.mapping.enabled>
        <authorisation.service.version>0.1.49</authorisation.service.version>
        <coredomain.version>17.104.4</coredomain.version>
        <cpp.structure.version>2.0.335</cpp.structure.version>
        <system.users.library.version>3.1.3</system.users.library.version>
        <referencedata.version>17.104.137</referencedata.version>
        <referencedata.offences.version>17.0.38</referencedata.offences.version>
        <system.enterprise-id.version>0.0.3</system.enterprise-id.version>
        <resulting.version>17.0.42</resulting.version>
        <progression.version>17.0.279</progression.version>
        <defence.version>17.0.87</defence.version>
        <criminal-court-public-model.version>${coredomain.version}</criminal-court-public-model.version>
        <notification.notify.version>17.0.24</notification.notify.version>
        <commons-text.version>1.10.0</commons-text.version>
        <awaility.version>1.7.0</awaility.version>
        <sjp.version>17.103.169</sjp.version>
        <json-smart.version>2.4.8</json-smart.version>
        <byte-buddy.version>1.12.19</byte-buddy.version>
        <domain.dsl.test.version>0.3.1</domain.dsl.test.version>
        <material.version>17.0.75</material.version>
        <stream-transformation-tool.version>6.4.5</stream-transformation-tool.version>
        <json-smart.version>2.4.9</json-smart.version>
        <stream-transformation-tool-anonymise>7.0.0</stream-transformation-tool-anonymise>
        <sonar.coverage.exclusions>
            **/uk/gov/moj/cpp/prosecutioncasefile/persistence/entity/**/*
            **/uk/gov/justice/api/**/*
            **/uk/gov/moj/cps/prosecutioncasefile/command/api/**/*
            **/uk/gov/moj/cpp/prosecution/casefile/json/schemas/**/*
            **/uk/gov/moj/cpp/prosecution/casefile/plea/json/schemas/**/*
            **/uk/gov/justice/api/resource/**/*
            **/uk/gov/justice/cps/prosecutioncasefile/**/*
            **/uk/gov/justice/core/courts/**/*
            **/uk/gov/moj/cpp/prosecution/casefile/application/json/schemas/**/*
            **/uk/gov/moj/cps/prosecutioncasefile/command/handler/**/*
            **/uk/gov/moj/cpp/cps/prosecutioncasefile/command/handler/staging/**/*
            **/uk/gov/moj/cps/prosecutioncasefile/domain/event/**/*
            **/uk/gov/moj/cpp/prosecution/casefile/event/**/*
        </sonar.coverage.exclusions>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>uk.gov.moj.cpp.common</groupId>
                <artifactId>system-users-library</artifactId>
                <version>${system.users.library.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.system.enterpriseid</groupId>
                <artifactId>system-enterprise-id</artifactId>
                <version>${system.enterprise-id.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.system.id-mapper</groupId>
                <artifactId>id-mapper-client</artifactId>
                <version>${cpp.platform-libraries.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.core.domain</groupId>
                <artifactId>common-core-domain</artifactId>
                <version>${coredomain.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons-text.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.core.domain</groupId>
                <artifactId>criminal-court-public-model</artifactId>
                <version>${coredomain.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.referencedata</groupId>
                <artifactId>referencedata-query-api</artifactId>
                <version>${referencedata.version}</version>
                <classifier>raml</classifier>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>domain-test-dsl</artifactId>
                <version>${domain.dsl.test.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice</groupId>
                <artifactId>stream-transformation-tool-api</artifactId>
                <version>${stream-transformation-tool.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice</groupId>
                <artifactId>stream-transformation-tool-api</artifactId>
                <version>${stream-transformation-tool.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.core.domain</groupId>
                <artifactId>common-core-domain</artifactId>
                <version>${coredomain.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.jayway.awaitility</groupId>
                <artifactId>awaitility</artifactId>
                <version>${awaility.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.minidev</groupId>
                <artifactId>json-smart</artifactId>
                <version>${json-smart.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.sjp</groupId>
                <artifactId>sjp-query-api</artifactId>
                <version>${sjp.version}</version>
                <classifier>raml</classifier>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.progression</groupId>
                <artifactId>progression-query-api</artifactId>
                <version>${progression.version}</version>
                <classifier>raml</classifier>
            </dependency>
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy</artifactId>
                <version>${byte-buddy.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice</groupId>
                <artifactId>stream-transformation-tool-anonymise</artifactId>
                <version>${stream-transformation-tool-anonymise}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>
        <site>
            <id>site</id>
            <url>${mvn.site.url}</url>
        </site>
    </distributionManagement>
    <modules>
        <module>prosecutioncasefile-viewstore</module>
        <module>prosecutioncasefile-command</module>
        <module>prosecutioncasefile-datatypes-common</module>
        <module>prosecutioncasefile-domain</module>
        <module>prosecutioncasefile-query</module>
        <module>prosecutioncasefile-validation-rules</module>
        <module>prosecutioncasefile-event</module>
        <module>prosecutioncasefile-service</module>
        <module>prosecutioncasefile-integration-test</module>
        <module>prosecutioncasefile-refdata</module>
        <module>prosecutioncasefile-event-sources</module>
        <module>prosecutioncasefile-common</module>
        <module>prosecutioncasefile-progression-service</module>
        <module>prosecutioncasefile-defence-service</module>
        <module>prosecutioncasefile-healthchecks</module>
    </modules>
</project>

